name: Scrape and Push
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node scrape
    - run: git add -A
    - run: git commit -m "Scraping"
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${ secrets.GITHUB_TOKEN }
        branch: gh-pages
