name: Scrape and Push
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: node scrape
    - run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: git config --global user.name "github-actions[bot]"
    - run: git commit -m "Scraping" -a
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: gh-pages
